<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>org.bahmni.module</groupId>
	<artifactId>medication-administration</artifactId>
	<version>2.0.0.ipd-SNAPSHOT</version>
	<packaging>pom</packaging>
	<name>Medication Administration</name>
	<description>Medication Administration module contains DB model and FHIR translation layers for medication administration</description>
	<url>https://demo.mybahmni.org/bahmni/home/index.html</url>

	<!-- GitHub Maven Package Repository for distribution management -->
	<distributionManagement>
		<repository>
			<id>github</id>
			<name>GitHub Packages</name>
			<url>https://maven.pkg.github.com/cureinternational/openmrs-module-medicationadministration</url>
		</repository>
	</distributionManagement>

	<licenses>
		<license>
			<name>Mozilla Public License 2.0 with Healthcare Disclaimer</name>
			<url>https://openmrs.org/license</url>
		</license>
	</licenses>
	<developers>
		<developer>
			<name>Bahmnitw</name>
			<email>bahmnicommunity@gmail.com</email>
			<organization>Bahmni</organization>
			<organizationUrl>https://github.com/Bahmni</organizationUrl>
		</developer>
	</developers>
	<scm>
		<connection>scm:git:git@github.com:Bahmni/openmrs-module-medication-administration.git</connection>
		<developerConnection>scm:git:https://github.com/Bahmni/openmrs-module-medication-administration.git</developerConnection>
		<url>https://github.com/Bahmni/openmrs-module-medication-administration</url>
	</scm>

	<modules>
		<module>api</module>
		<module>omod</module>
	</modules>

	<properties>
		<openmrsPlatformVersion>2.6.15</openmrsPlatformVersion>
		<springVersion>5.2.14.RELEASE</springVersion>
		<junitVersion>4.13</junitVersion>
		<powerMockVersion>2.0.7</powerMockVersion>
		<hamcrestVersion>1.3</hamcrestVersion>
		<mockitoVersion>3.5.11</mockitoVersion>
		<argLine>-Xmx1024m</argLine>
		<jacocoVersion>0.7.9</jacocoVersion>
		<lombokVersion>1.18.26</lombokVersion>
		<openmrsFhir2Version>2.5.0</openmrsFhir2Version>
	</properties>

	<build>
		<resources>
		<resource>
			<directory>src/main/resources</directory>
			<filtering>true</filtering>
			<includes>
				<include>**/*.xml</include>
				<include>**/*.txt</include>
				<include>**/*.properties</include>
			</includes>
		</resource>
		<resource>
			<directory>src/main/resources</directory>
			<filtering>false</filtering>
			<excludes>
				<exclude>**/*.xml</exclude>
				<exclude>**/*.txt</exclude>
				<exclude>**/*.properties</exclude>
			</excludes>
		</resource>
		</resources>
		<testResources>
			<testResource>
				<directory>src/test/resources</directory>
				<filtering>true</filtering>
				<includes>
					<include>**/*.xml</include>
					<include>**/*.txt</include>
					<include>**/*.properties</include>
				</includes>
			</testResource>
			<testResource>
				<directory>src/test/resources</directory>
				<filtering>false</filtering>
				<excludes>
					<exclude>**/*.xml</exclude>
					<exclude>**/*.txt</exclude>
					<exclude>**/*.properties</exclude>
				</excludes>
			</testResource>
		</testResources>
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-compiler-plugin</artifactId>
					<configuration>
						<target>1.8</target>
						<source>1.8</source>
					</configuration>
				</plugin>
				<plugin>
					<groupId>org.openmrs.maven.plugins</groupId>
					<artifactId>maven-openmrs-plugin</artifactId>
					<version>1.0.1</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-dependency-plugin</artifactId>
					<version>2.4</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-jar-plugin</artifactId>
					<version>2.4</version>
					<executions>
						<execution>
							<goals>
								<goal>test-jar</goal>
							</goals>
						</execution>
					</executions>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-surefire-plugin</artifactId>
					<version>2.10</version>
					<configuration>
						<includes>
							<include>**/*Test.java</include>
						</includes>
					</configuration>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.projectlombok</groupId>
				<artifactId>lombok</artifactId>
				<version>${lombokVersion}</version>
				<scope>provided</scope>
			</dependency>
			<!-- OpenMRS dependencies -->
			<dependency>
				<groupId>org.openmrs.api</groupId>
				<artifactId>openmrs-api</artifactId>
				<version>${openmrsPlatformVersion}</version>
				<type>jar</type>
				<scope>provided</scope>
				<exclusions>
					<exclusion>
						<groupId>javax.servlet</groupId>
						<artifactId>servlet-api</artifactId>
					</exclusion>
				</exclusions>
			</dependency>

			<dependency>
				<groupId>org.openmrs.web</groupId>
				<artifactId>openmrs-web</artifactId>
				<version>${openmrsPlatformVersion}</version>
				<type>jar</type>
				<scope>provided</scope>
			</dependency>


			<dependency>
				<groupId>org.openmrs.module</groupId>
				<artifactId>fhir2-api</artifactId>
				<version>${openmrsFhir2Version}</version>
				<scope>provided</scope>
			</dependency>

<!--			<dependency>-->
<!--				<groupId>org.openmrs.module</groupId>-->
<!--				<artifactId>fhir2-omod</artifactId>-->
<!--				<version>${openmrsFhir2Version}</version>-->
<!--				<scope>provided</scope>-->
<!--			</dependency>-->

			<dependency>
				<groupId>org.openmrs.test</groupId>
				<artifactId>openmrs-test</artifactId>
				<version>${openmrsPlatformVersion}</version>
				<type>pom</type>
				<scope>test</scope>
			</dependency>
			<dependency>
				<groupId>javax.servlet</groupId>
				<artifactId>servlet-api</artifactId>
				<version>2.5</version>
				<scope>test</scope>
			</dependency>

			<!-- Junit Test dependencies -->
			<dependency>
				<groupId>junit</groupId>
				<artifactId>junit</artifactId>
				<version>${junitVersion}</version>
				<exclusions>
					<exclusion>
						<groupId>org.hamcrest</groupId>
						<artifactId>hamcrest-core</artifactId>
					</exclusion>
				</exclusions>
				<scope>test</scope>
			</dependency>

			<!-- PowerMock Test dependencies -->
			<dependency>
				<groupId>org.powermock</groupId>
				<artifactId>powermock-api-mockito2</artifactId>
				<version>${powerMockVersion}</version>
				<scope>test</scope>
				<exclusions>
					<exclusion>
						<artifactId>mockito-all</artifactId>
						<groupId>org.mockito</groupId>
					</exclusion>
				</exclusions>
			</dependency>
			<dependency>
				<groupId>org.powermock</groupId>
				<artifactId>powermock-module-junit4</artifactId>
				<version>${powerMockVersion}</version>
				<scope>test</scope>
			</dependency>

			<!-- Mockito Test dependencies -->
			<dependency>
				<groupId>org.mockito</groupId>
				<artifactId>mockito-core</artifactId>
				<version>${mockitoVersion}</version>
				<exclusions>
					<exclusion>
						<groupId>org.hamcrest</groupId>
						<artifactId>hamcrest-core</artifactId>
					</exclusion>
				</exclusions>
				<scope>test</scope>
			</dependency>

			<dependency>
				<groupId>org.openmrs.api</groupId>
				<artifactId>openmrs-api</artifactId>
				<version>${openmrsPlatformVersion}</version>
				<type>test-jar</type>
				<scope>test</scope>
				<exclusions>
					<exclusion>
						<groupId>javax.servlet</groupId>
						<artifactId>servlet-api</artifactId>
					</exclusion>
				</exclusions>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<repositories>
		<repository>
			<id>openmrs-repo</id>
			<name>OpenMRS Nexus Repository</name>
			<url>https://mavenrepo.openmrs.org/public</url>
		</repository>
		<repository>
			<id>central</id>
			<name>Maven Repository Switchboard</name>
			<layout>default</layout>
			<url>https://repo1.maven.org/maven2</url>
		</repository>
	</repositories>

	<pluginRepositories>
		<pluginRepository>
			<id>openmrs-repo</id>
			<name>OpenMRS Nexus Repository</name>
			<url>https://mavenrepo.openmrs.org/public</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</pluginRepository>
	</pluginRepositories>


	<profiles>
		<profile>
			<id>release-sign-artifacts</id>
			<activation>
				<property>
					<name>performRelease</name>
					<value>true</value>
				</property>
			</activation>
			<build>
				<plugins>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-source-plugin</artifactId>
						<version>3.2.1</version>
						<executions>
							<execution>
								<goals>
									<goal>jar</goal>
								</goals>
							</execution>
						</executions>
					</plugin>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-javadoc-plugin</artifactId>
						<version>3.2.0</version>
						<executions>
							<execution>
								<goals>
									<goal>jar</goal>
								</goals>
							</execution>
						</executions>
					</plugin>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-gpg-plugin</artifactId>
						<version>1.6</version>
						<configuration>
						<!-- Prevent gpg from using pinentry programs -->
							<gpgArguments>
								<arg>--pinentry-mode</arg>
								<arg>loopback</arg>
							</gpgArguments>
						</configuration>
						<executions>
							<execution>
								<id>sign-artifacts</id>
								<phase>verify</phase>
								<goals>
									<goal>sign</goal>
								</goals>
							</execution>
						</executions>
					</plugin>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-failsafe-plugin</artifactId>
						<version>2.17</version>
						<executions>
							<execution>
								<goals>
									<goal>integration-test</goal>
									<goal>verify</goal>
								</goals>
								<configuration>
									<argLine>-Xmx512m</argLine>
									<includes>
										<include>**/*IT.java</include>
									</includes>
								</configuration>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
</project>
